version: '3.8'

services:
  app:
    build: .
    image: leaderapi:latest
    container_name: leaderapi
    ports:
      - "8081:10001"  # Ouvre le port 8081 du VPS vers le port 10001 de l'app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # C'EST LA LIGNE QUI RÃˆGLE TOUT
      - ASPNETCORE_URLS=http://+:10001
    env_file:
      - .env
    restart: unless-stopped
 