version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: humanapi:latest
    container_name: humanapi
    expose:
      - "8080"                # Visible uniquement dans le rÃ©seau Docker interne
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - .env
      # Optionnel:
      # - ConnectionStrings__MongoDB=mongodb+srv://USER:PASS@cluster0.xxx.mongodb.net/?retryWrites=true&w=majority
    restart: unless-stopped

  proxy:
    image: nginx:latest
    container_name: mon_nginx
    ports:
      - "80:80"               # Port 80 du VPS -> port 80 du conteneur Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped